#!/usr/bin/env python3
"""Shoot the featured demo snapshot tab by tab, and put the pictures where readers land.

The README described thirteen tabs in prose, and a reader had to open the demo to find out
what any of them looked like (issue #1: *less text, more screenshots*). This is the fix,
made so that it cannot go stale: every time the featured snapshot is published,
`publish-demo.sh` calls this, and it

  1. serves `demo/` over HTTP exactly as GitHub Pages will, opens `<slug>/review.html` in
     headless Chromium, clicks through every tab and takes one viewport-sized JPEG of each
     — `demo/<slug>/tour/<panel>.jpg`, beside the snapshot it shows, so a republish that
     wipes the snapshot wipes its pictures with it;
  2. rewrites the README's two managed regions — the hero shot under the intro (the links to
     the demos are the hand-written bullets at the top), and the tour (one full-width picture, one caption and one page per tab);
  3. rewrites the screenshot at the top of each tab's page under `docs/tabs/`;
  4. rewrites the featured block at the top of `demo/index.html`, the Pages landing page,
     so the site's root leads straight into the demo.

Everything outside the markers is hand-written and never touched. The one-line summary of
each tab lives in its own page (`docs/tabs/*.md`, the `>` line under the heading), so the
README table is assembled from the pages instead of repeating them.

Which snapshot is featured is written in exactly one place, the README's own marker —
`<!-- featured-demo:begin slug=demo -->` — so every link this writes is derived from it
rather than typed. `--feature SLUG` moves it.

Playwright is imported lazily: CI runs `--help` on every script here with no browser.
"""

from __future__ import annotations

import argparse
import functools
import html
import http.server
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
import threading
from pathlib import Path

HERE = Path(__file__).resolve().parent

VIEWPORT = {"width": 1440, "height": 900}
JPEG_QUALITY = 82

FEATURED_BEGIN = re.compile(r"<!-- featured-demo:begin(?: slug=([A-Za-z0-9_-]+))? -->")
FEATURED_END = "<!-- featured-demo:end -->"
TOUR_BEGIN = re.compile(r"<!-- tour:begin -->")
TOUR_END = "<!-- tour:end -->"
SHOT_BEGIN = re.compile(r"<!-- shot:begin -->")
SHOT_END = "<!-- shot:end -->"
LANDING_BEGIN = re.compile(r"<!-- featured:begin -->")
LANDING_END = "<!-- featured:end -->"

GENERATED = ("generated by `skills/human-review/scripts/readme-tour.py` on every publish "
             "of the featured snapshot — edits between these markers are overwritten")


# --------------------------------------------------------------------------------------
# text: pure functions, pinned by test_readme_tour.py


def featured_slug(readme: str) -> str | None:
    m = FEATURED_BEGIN.search(readme)
    return m.group(1) if m and m.group(1) else None


def replace_region(text: str, begin: re.Pattern, end: str, inner: str,
                   begin_marker: str | None = None) -> str:
    """Swap what sits between `begin` and `end` for `inner`; the markers themselves stay,
    unless `begin_marker` rewrites the opening one (it carries the featured slug)."""
    m = begin.search(text)
    if not m:
        raise ValueError(f"marker {begin.pattern!r} not found")
    stop = text.find(end, m.end())
    if stop < 0:
        raise ValueError(f"marker {end!r} not found after {begin.pattern!r}")
    opening = begin_marker if begin_marker is not None else m.group(0)
    return text[:m.start()] + opening + "\n" + inner.strip("\n") + "\n" + text[stop:]


def pages_base(repo: Path) -> str:
    """`https://<owner>.github.io/<repo>` from the origin remote, so a fork links to itself."""
    try:
        url = subprocess.run(["git", "-C", str(repo), "remote", "get-url", "origin"],
                             capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        url = ""
    m = re.search(r"github\.com[:/]([^/]+)/([^/]+?)(?:\.git)?/?$", url)
    if not m:
        return "https://victorrentea.github.io/human-review"
    return f"https://{m.group(1).lower()}.github.io/{m.group(2)}"


def read_tab_page(path: Path) -> dict | None:
    """The three facts the README needs from a tab's page: which panel it documents, its
    name, and its one-line summary. A page that names no panel is not a tab page."""
    text = path.read_text(encoding="utf-8")
    panel = re.search(r"<!-- panel: *([A-Za-z0-9_-]+) *-->", text)
    if not panel:
        return None
    title = re.search(r"^# +(.+?)\s*$", text, re.M)
    summary = re.search(r"^> +(.+?)\s*$", text, re.M)
    return {
        "panel": panel.group(1),
        "title": title.group(1) if title else panel.group(1),
        "summary": summary.group(1) if summary else "",
        "file": path.name,
    }


def render_featured(slug: str, base: str, title: str, hero: str | None) -> str:
    """The hero shot under the README's hand-written intro. The links to every demo sit in
    the bullets at the very top of the README; this only shows what one of them looks like."""
    live = f"{base}/{slug}/review.html"
    lines = [f"<!-- {GENERATED} -->"]
    if hero:
        lines += [f'<a href="{live}"><img src="{hero}" alt="{html.escape(title)} — '
                  f'the Review tab of the demo page" width="100%"></a>', ""]
    lines.append(f"<sub>**{html.escape(title)}**, Review tab — click to open it live. "
                 f"Every published snapshot: <{base}/></sub>")
    return "\n".join(lines)


def render_tour(slug: str, base: str, shots: list[dict], pages: dict[str, dict]) -> str:
    live = f"{base}/{slug}/review.html"
    blocks = []
    for shot in shots:
        page = pages.get(shot["panel"])
        img = f"demo/{slug}/tour/{shot['file']}"
        name = page["title"] if page else shot["title"]
        target = f"docs/tabs/{page['file']}" if page else img
        heading = f"### [{name}]({target})" if page else f"### {name}"
        caption = f"[open it live]({live}#{shot['panel']})"
        if page and page["summary"]:
            caption += f" — {page['summary']}"
        blocks += [
            heading,
            "",
            f'<a href="{target}"><img src="{img}" alt="{html.escape(name)} tab" width="100%"></a>',
            "",
            f"<sub>{caption}</sub>",
            "",
        ]
    return "\n".join([
        f"<!-- {GENERATED} -->",
        "One screenshot per tab of the demo, retaken on every publish.",
        "**Click a picture** for that tab's own page: what it shows, what it needs, how it works.",
        "",
        *blocks[:-1],
    ])


def render_tab_shot(slug: str, base: str, shot: dict | None, title: str) -> str:
    if not shot:
        return (f"<!-- {GENERATED} -->\n"
                f"*The featured demo (`{slug}`) has no {title} tab, so there is no screenshot "
                f"of it yet.*")
    live = f"{base}/{slug}/review.html#{shot['panel']}"
    return "\n".join([
        f"<!-- {GENERATED} -->",
        f'<a href="{live}"><img src="../../demo/{slug}/tour/{shot["file"]}" '
        f'alt="The {html.escape(title)} tab of the demo page" width="100%"></a>',
        "",
        f"[Open this tab in the live demo]({live}) · [all tabs](../../README.md#a-tour-one-tab-at-a-time)",
    ])


LANDING_CSS = """
  .featured { margin: 0 0 2.5rem; }
  .featured .hero { display: block; border: 1px solid var(--line); border-radius: 12px;
    overflow: hidden; background: var(--panel); transition: border-color .15s ease, transform .15s ease; }
  .featured .hero:hover { border-color: var(--accent); transform: translateY(-1px); }
  .featured .hero img { display: block; width: 100%; height: auto; }
  .featured .cta { display: flex; flex-wrap: wrap; align-items: center; gap: .6rem 1rem; margin: 1rem 0 1.2rem; }
  .featured .go { display: inline-block; background: var(--accent); color: var(--bg); font-weight: 600;
    text-decoration: none; padding: .6rem 1.15rem; border-radius: 999px; }
  .featured .go:hover { filter: brightness(1.1); }
  .featured .what { color: var(--muted); font-size: .92rem; }
  .featured .thumbs { list-style: none; margin: 0; padding: 0; display: grid;
    grid-template-columns: repeat(auto-fill, minmax(8.5rem, 1fr)); gap: .6rem; }
  .featured .thumbs a { display: block; text-decoration: none; color: var(--muted); font-size: .8rem; }
  .featured .thumbs img { display: block; width: 100%; aspect-ratio: 16 / 10; object-fit: cover;
    object-position: top; border: 1px solid var(--line); border-radius: 6px; margin-bottom: .2rem; }
  .featured .thumbs a:hover { color: var(--accent); }
  .featured .thumbs a:hover img { border-color: var(--accent); }
"""


def render_landing(slug: str, title: str, subtitle: str, shots: list[dict],
                   pages: dict[str, dict]) -> str:
    live = f"{slug}/review.html"
    hero = shots[0] if shots else None
    # The card is an <a>, and so is the hero: the subtitle keeps its text, loses its links.
    sub = re.sub(r"</?a\b[^>]*>", "", subtitle or "")
    out = [f"  <!-- {html.escape(GENERATED)} -->",
           f"  <style>{LANDING_CSS}  </style>",
           '  <section class="featured" aria-label="The live demo">']
    if hero:
        out.append(f'    <a class="hero" href="{live}"><img src="{slug}/tour/{hero["file"]}" '
                   f'alt="{html.escape(title)} — the review page, open on its first tab"></a>')
    out.append('    <p class="cta">'
               f'<a class="go" href="{live}">Open the live demo →</a>'
               f'<span class="what"><b>{html.escape(title)}</b>'
               + (f" — {sub}" if sub else "") + "</span></p>")
    if shots:
        out.append('    <ul class="thumbs">')
        for shot in shots:
            page = pages.get(shot["panel"])
            name = html.escape(page["title"] if page else shot["title"])
            out.append(f'      <li><a href="{live}#{shot["panel"]}">'
                       f'<img src="{slug}/tour/{shot["file"]}" alt="" loading="lazy">{name}</a></li>')
        out.append("    </ul>")
    out.append("  </section>")
    return "\n".join(out)


def ensure_landing_region(text: str) -> str:
    """First run: open the featured region under the page's lede, above everything else."""
    if LANDING_BEGIN.search(text):
        return text
    m = re.search(r'<p class="lede">.*?</p>\n', text, re.S)
    if not m:
        raise ValueError("demo/index.html has no <p class=\"lede\"> to put the demo under")
    return (text[:m.end()] + "\n  <!-- featured:begin -->\n  <!-- featured:end -->\n"
            + text[m.end():])


# --------------------------------------------------------------------------------------
# pictures


def _shoot_module():
    """shoot-review.py already knows how to settle a panel, wake its lazy images and give a
    video a first frame; borrow that rather than keep a second copy that drifts."""
    spec = importlib.util.spec_from_file_location("shoot_review", HERE / "shoot-review.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class _Quiet(http.server.SimpleHTTPRequestHandler):
    """Static files, plus the one thing `SimpleHTTPRequestHandler` lacks and Pages has:
    byte ranges. Without them Chromium cannot seek the feature video, and the Demo tab was
    shot on its title card with a spinner over it."""

    def log_message(self, *args):  # noqa: D401 — a request log per image is only noise
        pass

    def send_head(self):
        rng = re.fullmatch(r"bytes=(\d*)-(\d*)", self.headers.get("Range", "").strip())
        path = Path(self.translate_path(self.path))
        if not rng or not path.is_file():
            return super().send_head()
        size = path.stat().st_size
        first, last = rng.groups()
        if first:
            start, end = int(first), int(last) if last else size - 1
        else:
            start, end = max(0, size - int(last or 0)), size - 1
        end = min(end, size - 1)
        if start > end:
            self.send_error(416)
            return None
        f = path.open("rb")
        f.seek(start)
        self.send_response(206)
        self.send_header("Content-Type", self.guess_type(str(path)))
        self.send_header("Content-Range", f"bytes {start}-{end}/{size}")
        self.send_header("Content-Length", str(end - start + 1))
        self.send_header("Accept-Ranges", "bytes")
        self.end_headers()
        self._remaining = end - start + 1
        return f

    def copyfile(self, source, outputfile):
        remaining = getattr(self, "_remaining", None)
        if remaining is None:
            return super().copyfile(source, outputfile)
        self._remaining = None
        while remaining > 0:
            chunk = source.read(min(64 * 1024, remaining))
            if not chunk:
                break
            outputfile.write(chunk)
            remaining -= len(chunk)


def serve(root: Path):
    handler = functools.partial(_Quiet, directory=str(root))
    server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    return server


# JS click: a mouse click would leave the pointer on the tab strip, and the strip's hover
# tooltips would be in every picture.
CLICK_TAB_JS = "(i) => document.querySelectorAll('.tabstrip button.tab')[i].click()"

# After the seek, Chromium paints its buffering spinner over the frame until enough data
# is in to play on from it; wait for that (a ceiling, not a pace). The spinner then fades
# out inside the controls' shadow DOM, which FREEZE_CSS cannot reach and nothing reports,
# so a panel with a video is given SPINNER_FADE_MS more before it is shot.
SPINNER_FADE_MS = 2000
VIDEO_READY_JS = """
async (sel) => {
  const scope = sel ? document.querySelector(sel) : null;
  const videos = scope ? Array.from(scope.querySelectorAll('video')) : [];
  await Promise.all(videos.map((v) => v.readyState >= 3 ? null : new Promise((r) => {
    v.addEventListener('canplay', r, {once: true});
    setTimeout(r, 8000);
  })));
  return videos.length;
}
"""

# The Sequence tab opens with every test pair folded, which is right for a reader and makes
# a picture of five grey rows. Unfold the first pair, so the shot shows a diagram beside the
# test that drew it — which is what the tab is for.
UNFOLD_FIRST_JS = """
(sel) => {
  const scope = sel ? document.querySelector(sel) : null;
  if (!scope || scope.querySelector('details.testpair[open]')) return false;
  const first = scope.querySelector('details.testpair');
  if (first) first.open = true;
  return Boolean(first);
}
"""


def shoot(demo_root: Path, slug: str, out_dir: Path) -> list[dict]:
    sr = _shoot_module()
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        raise SystemExit(
            "readme-tour: playwright is not installed for this interpreter.\n"
            "             publish-demo.sh provisions it; or: pip install playwright && "
            "playwright install chromium")

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    server = serve(demo_root)
    url = f"http://127.0.0.1:{server.server_address[1]}/{slug}/review.html"
    shots: list[dict] = []
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch()
            context = browser.new_context(viewport=VIEWPORT, device_scale_factor=1,
                                          color_scheme="light", reduced_motion="reduce")
            page = context.new_page()
            page.goto(url, wait_until="load")
            page.add_style_tag(content=sr.FREEZE_CSS)
            try:
                page.wait_for_load_state("networkidle", timeout=15000)
            except Exception:  # noqa: BLE001 — a page that never idles is still shootable
                pass
            tabs = page.evaluate(sr.TAB_META_JS)
            if not tabs:
                raise SystemExit(f"readme-tour: {url} has no tab strip")
            for i, tab in enumerate(tabs):
                panel = tab["panel"] or sr.slugify(tab["title"])
                selector = f"#{tab['panel']}" if tab["panel"] else None
                page.evaluate(CLICK_TAB_JS, i)
                if selector:
                    page.wait_for_selector(selector, state="visible", timeout=15000)
                page.evaluate(UNFOLD_FIRST_JS, selector)
                page.evaluate(sr.EAGER_IMAGES_JS, selector)
                page.evaluate(sr.NEUTRALIZE_VIDEO_JS, selector)
                if page.evaluate(VIDEO_READY_JS, selector):
                    page.wait_for_timeout(SPINNER_FADE_MS)
                page.evaluate("() => window.scrollTo(0, 0)")
                sr.wait_settled(page, selector)
                name = f"{panel}.jpg"
                page.screenshot(path=str(out_dir / name), type="jpeg", quality=JPEG_QUALITY)
                size = (out_dir / name).stat().st_size
                print(f"  {name:<18} {tab['title']}  ({size // 1024} KB)", file=sys.stderr)
                shots.append({"panel": panel, "title": tab["title"], "file": name})
            context.close()
            browser.close()
    finally:
        server.shutdown()
    return shots


# --------------------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="readme-tour.py",
        description=("Screenshot every tab of the featured demo snapshot and refresh the "
                     "README tour, the per-tab pages under docs/tabs/ and the featured block "
                     "on the Pages landing page. Called by publish-demo.sh."))
    parser.add_argument("--repo", default=os.environ.get("HUMAN_REVIEW_REPO",
                                                         str(Path.home() / "workspace/human-review")),
                        help="checkout of human-review (default: $HUMAN_REVIEW_REPO or ~/workspace/human-review)")
    parser.add_argument("--slug", default="",
                        help="only act if this is the featured snapshot (what publish-demo.sh passes)")
    parser.add_argument("--feature", default="",
                        help="make this snapshot the featured one, then refresh everything")
    parser.add_argument("--no-shoot", action="store_true",
                        help="keep the existing pictures, only rewrite the text around them")
    args = parser.parse_args(argv)

    repo = Path(args.repo).expanduser().resolve()
    readme_path = repo / "README.md"
    readme = readme_path.read_text(encoding="utf-8")
    featured = args.feature or featured_slug(readme)
    if not featured:
        raise SystemExit("readme-tour: README.md has no '<!-- featured-demo:begin slug=… -->' "
                         "marker; pass --feature SLUG once to set it")
    if args.slug and args.slug != featured:
        print(f"readme-tour: {args.slug} is not the featured snapshot ({featured}); "
              f"README left alone", file=sys.stderr)
        return 0

    snap = repo / "demo" / featured
    if not (snap / "review.html").is_file():
        raise SystemExit(f"readme-tour: no snapshot at {snap}")
    tour_dir = snap / "tour"
    manifest_path = tour_dir / "tour.json"

    content = {}
    try:
        content = json.loads((snap / "content.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        pass
    title = re.sub(r"<[^>]+>", "", content.get("title") or featured).strip()
    subtitle = content.get("subtitle") or ""

    if args.no_shoot:
        if not manifest_path.is_file():
            raise SystemExit(f"readme-tour: --no-shoot, but there are no pictures in {tour_dir}")
        shots = json.loads(manifest_path.read_text(encoding="utf-8"))["shots"]
    else:
        print(f"readme-tour: shooting demo/{featured}/review.html, tab by tab", file=sys.stderr)
        shots = shoot(repo / "demo", featured, tour_dir)
        manifest_path.write_text(json.dumps({"slug": featured, "title": title, "shots": shots},
                                            indent=2) + "\n", encoding="utf-8")

    base = pages_base(repo)
    pages: dict[str, dict] = {}
    page_paths: dict[str, Path] = {}
    for path in sorted((repo / "docs" / "tabs").glob("*.md")):
        info = read_tab_page(path)
        if info:
            pages[info["panel"]] = info
            page_paths[info["panel"]] = path

    by_panel = {s["panel"]: s for s in shots}
    hero = f"demo/{featured}/tour/{shots[0]['file']}" if shots else None

    readme = replace_region(readme, FEATURED_BEGIN, FEATURED_END,
                            render_featured(featured, base, title, hero),
                            begin_marker=f"<!-- featured-demo:begin slug={featured} -->")
    readme = replace_region(readme, TOUR_BEGIN, TOUR_END,
                            render_tour(featured, base, shots, pages))
    readme_path.write_text(readme, encoding="utf-8")

    for panel, path in page_paths.items():
        text = path.read_text(encoding="utf-8")
        if not SHOT_BEGIN.search(text):
            print(f"  ! {path.name}: no shot markers, left alone", file=sys.stderr)
            continue
        text = replace_region(text, SHOT_BEGIN, SHOT_END,
                              render_tab_shot(featured, base, by_panel.get(panel),
                                              pages[panel]["title"]))
        path.write_text(text, encoding="utf-8")
    for shot in shots:
        if shot["panel"] not in pages:
            print(f"  ! tab '{shot['title']}' ({shot['panel']}) has no page under docs/tabs/",
                  file=sys.stderr)

    landing_path = repo / "demo" / "index.html"
    landing = ensure_landing_region(landing_path.read_text(encoding="utf-8"))
    landing = replace_region(landing, LANDING_BEGIN, LANDING_END,
                             render_landing(featured, title, subtitle, shots, pages))
    landing_path.write_text(landing, encoding="utf-8")

    print(f"readme-tour: {len(shots)} tabs of '{featured}' -> README.md, docs/tabs/, "
          f"demo/index.html", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
